[files]
extend-exclude = [
  "crates/datashed/tests/data/*.txt",
  "crates/datashed/tests/it/*.rs",
  "crates/datashed/src/document.rs",
  "crates/datashed/src/dtypes.rs",
  "crates/unhyphen/src/lib.rs",
]
