[files]
extend-exclude = [
  "crates/datashed-cli/tests/data/*.txt",
  "crates/datashed-cli/tests/it/*.rs",
  "crates/datashed-cli/src/document.rs",
  "crates/datashed-cli/src/dtypes.rs",
  "crates/unhyphen/src/lib.rs",
]
