[workspace]
members = ["crates/datashed"]
resolver = "3"

[workspace.package]
authors = ["Nico Wagner <n.wagner@dnb.de>"]
rust-version = "1.87"
license = "EUPL-1.2"
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1.0" }
approx = { version = "0.5" }
assert_cmd = { version = "2.0" }
assert_fs = { version = "1.1" }
bstr = { version = "1.12" }
clap_complete = { version = "4.5" }
hashbrown = { version = "0.15" }
indicatif = { version = "0.17", features = ["rayon"] }
lingua = { version = "1.7" }
predicates = { version = "3.1" }
rayon = { version = "1.10" }
regex = { version = "1.11" }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.10" }
tar = { version = "0.4" }
toml_edit = { version = "0.22", features = ["serde"] }
unicode_categories = { version = "0.1" }
unicode-normalization = { version = "0.1" }
walkdir = { version = "2.5" }

[workspace.dependencies.clap]
version = "4.5"
features = ["derive","wrap_help","env","cargo"]

[workspace.dependencies.flate2]
version = "1.1"
default-features = false
features = ["zlib-rs"]

[workspace.dependencies.polars]
version = "0.48"
# git = "https://github.com/pola-rs/polars"
# branch = "main"
features = [
  "decompress",
  "dtype-slim",
  "ipc",
  "is_in",
  "lazy",
  "semi_anti_join",
  "sql",
]
