[workspace]
members = ["crates/datashed"]
resolver = "3"

[workspace.package]
authors = ["Nico Wagner <n.wagner@dnb.de>"]
rust-version = "1.89"
license = "EUPL-1.2"
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1.0" }
approx = { version = "0.5" }
assert_cmd = { version = "2.0" }
assert_fs = { version = "1.1" }
bstr = { version = "1.12" }
clap_complete = { version = "4.5" }
hashbrown = { version = "0.15" }
indexmap = { version = "2.10", features = ["serde"] }
indicatif = { version = "0.18", features = ["rayon"] }
isbn = { version = "0.4" }
lingua = { version = "1.7" }
ndarray-stats = { version = "0.6" }
ndarray = { version = "0.16" }
owo-colors = { version = "4.2" }
predicates = { version = "3.1" }
rayon = { version = "1.10" }
regex = { version = "1.11" }
semver = { version = "1.0", features = ["serde"] }
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.10" }
tar = { version = "0.4" }
toml_edit = { version = "0.22", features = ["serde"] }
unicode_categories = { version = "0.1" }
unicode-normalization = { version = "0.1" }
walkdir = { version = "2.5" }

[workspace.dependencies.pica-record]
git = "https://github.com/deutsche-nationalbibliothek/pica-rs.git"
version = "1.2"
features = ["serde"]

[workspace.dependencies.clap]
version = "4.5"
features = ["derive","wrap_help","env","cargo"]

[workspace.dependencies.flate2]
version = "1.1"
default-features = false
features = ["zlib-rs"]

[workspace.dependencies.polars]
version = "0.50"
features = [
  "decompress",
  "dtype-slim",
  "dtype-u8",
  "dtype-u16",
  "ipc",
  "is_in",
  "lazy",
  "semi_anti_join",
  "sql",
]

[profile.release]
lto = "fat"
panic = "abort"
debug = "none"
codegen-units = 1
opt-level = 3
strip = true
