[package]
name = "dataset-core"
version = "0.1.0"
authors.workspace = true
rust-version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bstr = { workspace = true }
polars = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml_edit = { workspace = true, features = ["serde"] }
