[package]
name = "dataset-cli"
version = "0.1.0"
authors.workspace = true
rust-version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "dataset"
path = "src/main.rs"

[features]
default = []
performant = [
  "dataset-core/performant",
  "polars/cse",
  "polars/performant",
]

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
dataset-core = { workspace = true }
indicatif = { workspace = true }
polars = { workspace = true }
rayon = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
toml_edit = { workspace = true }
url = { workspace = true }
