[package]
name = "datashed"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "datashed"
path = "src/lib.rs"

[[bin]]
name = "datashed"
path = "src/bin/datashed/main.rs"

[features]
default = ["performant"]
performant = ["polars/cse", "pica-record/performant"]
nightly = ["polars/nightly", "hashbrown/nightly", "pica-record/nightly"]

[dependencies]
anyhow = { workspace = true }
bstr = { workspace = true }
clap_complete = { workspace = true }
clap = { workspace = true }
flate2 = { workspace = true }
hashbrown = { workspace = true }
indicatif = { workspace = true }
lingua = { workspace = true }
pica-record = { workspace = true }
polars = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
toml_edit = { workspace = true }
unicode_categories = { workspace = true }
unicode-normalization = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
approx = { workspace = true }
assert_cmd = { workspace = true }
assert_fs = { workspace = true }
predicates = { workspace = true }


