name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "-Dwarnings"
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1


permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        target:
          - { os: ubuntu-latest, toolchain: stable, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: beta, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: nightly, triple: x86_64-unknown-linux-gnu }
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.target.toolchain }}
          targets: ${{ matrix.target.triple }}
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        if: ${{ matrix.target.toolchain != 'nightly' }}
        run: |
            cargo nextest run --workspace
            cargo test --doc --workspace --no-fail-fast
      - name: Run tests (nightly)
        if: ${{ matrix.target.toolchain == 'nightly' }}
        run: |
            cargo nextest run --workspace --all-features
            cargo test --doc --workspace --all-features --no-fail-fast

  ci:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: exit 0
